- name: Install the mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Enable and start mysql service
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: started 

- name: setup root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1